from building import *

cwd = GetCurrentDir()
src = Glob('*.cpp') + Glob('*.c')
path = [cwd]

LOCAL_CXXFLAGS = ' -O3'

# 增加对 C++ 的支持定义
group = DefineGroup('ICP', src, 
        depend = ['RT_USING_CPLUSPLUS'], 
        CPPPATH = path,
        LOCAL_CXXFLAGS = LOCAL_CXXFLAGS,
        LIBS = ['m'])

Return('group')