from building import *

cwd = GetCurrentDir()
src = Glob('*.cpp')
CPPPATH = [cwd]
LOCAL_CXXFLAGS = '-O3'
LIBS = ['m']

group = DefineGroup('ICP', src, depend=['RT_USING_CPLUSPLUS'],
                    CPPPATH=CPPPATH, LOCAL_CXXFLAGS=LOCAL_CXXFLAGS, LIBS=LIBS)

Return('group')
