from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]

group = DefineGroup('EWMA',
                    src,
                    depend = [''],
                    CPPPATH = path,
                    LIBS = ['m'])

Return('group')
