/**
 * @file test_schedule.h
 * @brief Schedulability verification test for RTOS-Bench
 * @details Implements UUniFast-based task set generation and deadline miss rate testing
 *          according to industrial RTOS benchmark standards.
 *
 * Usage: rtbench test-schedule
 *
 * The test performs:
 * 1. WCET measurement for all registered workloads
 * 2. Task set generation using UUniFast algorithm (30%-100% utilization, step 10%)
 * 3. Concurrent execution of periodic tasks for 3 cycles per gradient
 * 4. Deadline miss rate calculation and final score computation
 *
 * Final Score = 100 * (1 - Average_MR)
 */

#ifndef TEST_SCHEDULE_H
#define TEST_SCHEDULE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Configuration constants.
 *
 * Defaults reflect the acceptance-report baseline: 9 industrial workloads, real
 * (uncapped) WCET measured over a few iterations, cycles=3, and the full 30%-
 * 100% step-10 gradient sweep (8 gradients).  This is the lightweight profile
 * suited to embedded boards -- it is the DEFAULT now, no explicit --quick
 * needed -- while still exercising every workload and every gradient. */
#define TEST_SCHEDULE_MAX_TASKS      16
#define TEST_SCHEDULE_CYCLES         3
#define TEST_SCHEDULE_WCET_ITERATIONS 5
#define TEST_SCHEDULE_UTIL_START     30
#define TEST_SCHEDULE_UTIL_END       100
#define TEST_SCHEDULE_UTIL_STEP      10
#define TEST_SCHEDULE_NUM_GRADIENTS  8  /* (100-30)/10 + 1 */

/* Legacy --quick smoke profile (single 60% gradient, 1 cycle).  The normal
 * defaults above are already the lightweight embedded profile, so --quick is
 * now only an even-faster single-gradient smoke check, not the way to make the
 * test board-friendly. */
#define TEST_SCHEDULE_QUICK_CYCLES         1
#define TEST_SCHEDULE_QUICK_WCET_ITERATIONS 1
#define TEST_SCHEDULE_QUICK_UTIL_START     60
#define TEST_SCHEDULE_QUICK_UTIL_END       60
#define TEST_SCHEDULE_QUICK_UTIL_STEP      60

/* Board-adaptable period upper bound.
 * UUniFast yields very long periods at low utilization, which make a gradient
 * barely run any jobs and stretch wall-clock time.  Default = UINT64_MAX (no
 * clamp) so all existing boards keep their current scheduling behaviour and
 * scores.  A board may tighten it with a single compile define, e.g.:
 *   -DTEST_SCHEDULE_MAX_PERIOD_NS=10000000000ULL   (10 s, used by DONGTU) */
#ifndef TEST_SCHEDULE_MAX_PERIOD_NS
#define TEST_SCHEDULE_MAX_PERIOD_NS  UINT64_MAX
#endif

/* Overall watchdog backstop (milliseconds).
 * Per-task stall detection (no job progress for K of the task's own periods)
 * is the primary "stuck" signal; see wait_all_tasks_deadline().  This total
 * budget is only the outermost absolute backstop guaranteeing the whole run
 * terminates and reaches Phase 3 / Final Score even in pathological cases the
 * stall logic does not cover.  Kept under the telnet acceptance timeout.
 * There is intentionally no fixed per-gradient wall-clock budget: slow-but-
 * progressing gradients must finish rather than be cut at an arbitrary point.
 * Override per board with -DTEST_SCHEDULE_TOTAL_BUDGET_MS if needed. */
#ifndef TEST_SCHEDULE_TOTAL_BUDGET_MS
#define TEST_SCHEDULE_TOTAL_BUDGET_MS     (15u * 60u * 1000u)  /* 15 min overall */
#endif

/* Board fallback — workload allow / exclude lists (comma-separated names).
 * A workload that HARD-faults the OS (page fault / OOM) cannot be caught by the
 * in-process watchdog; the robust fallback is to never run it.  Define either
 * list at build time so acceptance always completes with a valid score over the
 * remaining REAL workloads.  Both unset (default) => every workload runs.
 *   -DTEST_SCHEDULE_WORKLOAD_ALLOWLIST="fast,pid,cusum,ewma"   (only these run)
 *   -DTEST_SCHEDULE_WORKLOAD_EXCLUDE="icp,ekf"                 (all but these)
 * Implemented in test_schedule.c:is_workload_allowed(), applied in Phase 1
 * before any workload is executed. */

/**
 * @brief Task configuration generated by UUniFast
 */
struct schedule_task_config {
	const char *name;           /**< Workload name */
	int workload_idx;           /**< Index in workload registry */
	uint64_t wcet_ns;           /**< Measured WCET in nanoseconds */
	double utilization;         /**< Assigned utilization (0.0-1.0) */
	uint64_t period_ns;         /**< Period = wcet / utilization */
	uint64_t deadline_ns;       /**< Deadline (= period for implicit deadline) */
};

/**
 * @brief Per-task runtime statistics
 */
struct schedule_task_stats {
	const char *name;           /**< Task name */
	uint64_t total_jobs;        /**< Total job activations */
	uint64_t deadline_misses;   /**< Jobs that missed deadline */
	uint64_t total_response_ns; /**< Sum of response times for avg calculation */
	uint64_t max_response_ns;   /**< Maximum observed response time */
};

/**
 * @brief Result for one utilization gradient
 */
struct schedule_gradient_result {
	int utilization_percent;    /**< Target utilization (30, 40, ..., 100) */
	double actual_utilization;  /**< Measured actual utilization */
	double miss_rate;           /**< (total_misses / total_jobs) */
	uint64_t total_jobs;        /**< Total jobs executed */
	uint64_t total_misses;      /**< Total deadline misses */
	struct schedule_task_stats task_stats[TEST_SCHEDULE_MAX_TASKS];
	int num_tasks;              /**< Number of tasks in this gradient */
};

/**
 * @brief Final test result
 */
struct test_schedule_result {
	int num_gradients;          /**< Number of gradients tested */
	struct schedule_gradient_result gradients[TEST_SCHEDULE_NUM_GRADIENTS];
	double average_miss_rate;   /**< Average MR across all gradients */
	double final_score;         /**< 100 * (1 - average_MR) */
};

/**
 * @brief Run the complete test-schedule benchmark
 * @return 0 on success, negative on error
 *
 * This function:
 * 1. Measures WCET for all registered workloads
 * 2. For each utilization gradient (30%-100%):
 *    - Generates task set using UUniFast
 *    - Runs concurrent periodic tasks
 *    - Records deadline misses
 * 3. Calculates and prints final score
 */
int test_schedule_run(void);

/**
 * @brief Run test-schedule with custom parameters
 * @param cycles Number of cycles per task (default: 3)
 * @param util_start Starting utilization percentage (default: 30)
 * @param util_end Ending utilization percentage (default: 100)
 * @param util_step Utilization step percentage (default: 10)
 * @return 0 on success, negative on error
 */
int test_schedule_run_custom(int cycles, int util_start, int util_end, int util_step);

/**
 * @brief Get the last test result
 * @return Pointer to the result structure (valid until next test_schedule_run)
 */
const struct test_schedule_result *test_schedule_get_result(void);

#ifdef __cplusplus
}
#endif

#endif /* TEST_SCHEDULE_H */
