image: ubuntu:rolling

pages:
  script:
    - apt-get -yq update && apt-get install -yq doxygen graphviz make git bash sed
    - DOCS_ONLY=1 make setup
    - make docs
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  only:
    - main
