image: alpine

pages:
    script:
    - apk update && apk add doxygen graphviz make git
    - make -C docs
    - mv docs/html/ public/
    artifacts:
        paths:
            - public
    only:
    - main
