image: alpine

pages:
  script:
    - apk update && apk add doxygen graphviz make git bash sed
    - DOCS_ONLY=1 make setup
    - make docs
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  only:
    - main
