from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, os.path.join(cwd, 'include_imgs')]
LIBS = ['m']

group = DefineGroup('FAST', src, depend=[''], CPPPATH=CPPPATH, LIBS=LIBS)

Return('group')
