# STRESS Module SConscript
# Independent subcommand for power consumption / stress testing
# Usage: rtbench test-stress -s <stressor> -t <duration>

from building import *
import os

cwd = GetCurrentDir()

# Core stress-ng sources
src = [
    'stress_bench.c',
    'common/stress-ng.c',
    'common/core-helper.c',
    'common/stress_stored_job.c',
]

# OSAL layer
src += Glob('osal/*.c')

# Stressor implementations
src += Glob('stressor/*.c')

CPPPATH = [
    cwd,
    cwd + '/common',
    cwd + '/osal',
]

LOCAL_CPPDEFINES = []

# RT-Thread platform
if GetDepend(['RT_THREAD_PRIORITY_32']) or GetDepend(['RT_THREAD_PRIORITY_256']) or GetDepend(['RT_USING_LIBC']):
    LOCAL_CPPDEFINES.append('RT_THREAD_PLATFORM')

group = DefineGroup('rtbench_stress', src,
                    depend=[''],
                    CPPPATH=CPPPATH,
                    LOCAL_CPPDEFINES=LOCAL_CPPDEFINES)

Return('group')
