from building import *
import os

cwd = GetCurrentDir()

src = Glob('EKF/*.cpp') + Glob('geo/*.cpp') + Glob('geo_lookup/*.cpp') + Glob('*.cpp')

CPPPATH = [
    cwd,
    os.path.join(cwd, 'include'),
    os.path.join(cwd, 'include', 'matrix'),
    os.path.join(cwd, 'geo_lookup'),
    os.path.join(cwd, 'geo')
]

CPPDEFINES = ['ECL_STANDALONE']
LIBS = ['m']

group = DefineGroup('EKF', src, depend=['RT_USING_CPLUSPLUS'],
                    CPPPATH=CPPPATH, CPPDEFINES=CPPDEFINES, LIBS=LIBS)

Return('group')
