# RTOS-Bench Workloads SConscript
from building import *
import os

cwd = GetCurrentDir()
objs = []

# Build rtbench_workloads.cpp which registers all workloads
src = Glob('rtbench_workloads.cpp')
CPPPATH = [cwd]
group = DefineGroup('rtbench_workloads', src, depend=[''], CPPPATH=CPPPATH)
objs.append(group)

# Auto-discover workload subdirectories with SConscript
for item in os.listdir(cwd):
    path = os.path.join(cwd, item)
    sconscript = os.path.join(path, 'SConscript')
    if os.path.isdir(path) and os.path.isfile(sconscript):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
