#################################
# Original Author: Sravanthi Kota Venkata
#################################

# Define MATLAB-PATH with the path to the MATLAB package
MATLAB_PATH = /pkg/bin/matlab
ifeq ($(filter matlab-run,$(MAKECMDGOALS)),matlab-run)
ifneq ($(wildcard $(MATLAB_PATH)),$(MATLAB_PATH))
$(error Please set the appropriate MATLAB path in MATLAB_PATH variable)
endif
endif

ifeq ($(filter mcc-run,$(MAKECMDGOALS)),mcc-run)
ifneq ($(wildcard $(MATLAB_PATH)),$(MATLAB_PATH))
$(error Please set the appropriate MATLAB path in MATLAB_PATH variable)
endif
endif

CC=gcc

override CFLAGS += -DGCC -D$(INPUT)

ifdef CORE
ifeq ($(CORE),CORTEX_A53)
override CFLAGS +=-DAARCH64 -DCORTEX_A53
endif
endif

ifdef CHECK_OUTPUT
override CFLAGS+= -DCHECK
endif

BASE_DIR := $(TOP_DIR)/../generator
COMMON_DIR := $(TOP_DIR)/common/c
M_COMMON := $(TOP_DIR)/common/matlab
M_TOOLBOX=$(TOP_DIR)/common/toolbox
TIMING_DIR := $(TOP_DIR)/cycles/$(BMARK)
MTIMING_DIR := $(TOP_DIR)/cycles/$(BMARK)
BMARK_DIR := $(TOP_DIR)/benchmarks/$(BMARK)

#The options set below and specific to each benchmark. Disparity takes 2 input images, whereas Tracking can take any >1 input images =.

# Variables exported from the benchmark specific Makefiles:
# BMARK
# INPUT - sqcif/qcif/cif

# Matlab source, data and result directory

M_DIR=$(BMARK_DIR)/src/matlab
M_DATA=$(BMARK_DIR)/data/$(INPUT)
M_RESULT=$(BMARK_DIR)/result

# C source, data and result directory

C_DIR=$(BMARK_DIR)/src/c
DATA_DIR=$(BMARK_DIR)/data/$(INPUT)
C_RESULT=$(M_RESULT)

# Source files for C and Common folders

BASE_SRC := $(wildcard $(BASE_DIR)/*.c)
C_SRC := $(wildcard $(C_DIR)/*.c)
COMMON_SRC := $(wildcard $(COMMON_DIR)/*.c)

# RULES
EXE =
INCLUDES = -I$(COMMON_DIR) -I$(C_DIR) -I$(BASE_DIR)
COMPILE_C = $(CC) $(CFLAGS) -O2 $(INCLUDES) -Wl,--wrap=malloc -Wl,--wrap=mmap
C_LIBS = -lrt -lm -pthread
#COMPILE_C = $(CC) $(CFLAGS) -DGENERATE_OUTPUT -lm -O2 $(INCLUDES) -Wl,--wrap=malloc -Wl,--wrap=mmap
COMPILE_G = $(CC) $(CFLAGS) -g -lrt -lm -pthread $(INCLUDES) -Wl,--wrap=malloc -Wl,--wrap=mmap
COMPILE_PG = $(COMPILE_G) -pg


c-run: compile
	@echo -e "Data set\t\t- $(INPUT)"
	@mkdir -p $(TIMING_DIR)
	@./$(BMARK)$(EXE) $(BMARK_OPTIONS) -b $(DATA_DIR) $(C_RESULT) | tee -i $(TIMING_DIR)/C_$(INPUT).txt

debug:
	@echo Running Debug C Version of the benchmark
	@$(COMPILE_G) $(BASE_SRC) $(COMMON_SRC) $(C_SRC) -o $(BMARK)$(EXE)

debug-valgrind: debug
	@valgrind --leak-check=full -s ./$(BMARK)$(EXE) $(BMARK_OPTIONS) -b $(DATA_DIR) $(C_RESULT)  -b $(DATA_DIR)

debug-gdb: debug
	@gdb --args ./$(BMARK)$(EXE) $(BMARK_OPTIONS) -b $(DATA_DIR) $(C_RESULT)  -b $(DATA_DIR)

debug-asan:
	@echo Running Debug C Version of the benchmark
	@$(COMPILE_G) -fsanitize=address $(BASE_SRC) $(COMMON_SRC) $(C_SRC) -o $(BMARK)$(EXE)
	@./$(BMARK)$(EXE) $(BMARK_OPTIONS) -b $(DATA_DIR) $(C_RESULT)


profile: compile-prof
	@echo -e "Data set\t\t- $(INPUT)"
	@./$(BMARK)$(EXE) $(BMARK_OPTIONS) -b $(DATA_DIR) $(C_RESULT)
	@gprof $(BMARK)$(EXE)


compile: $(C_SRC)
	@echo
	@echo -e "Benchmark\t\t- $(BMARK)"
	@echo -e "${COMPILE_C}"
	@$(COMPILE_C) $(BASE_SRC) $(COMMON_SRC) $(C_SRC) -o $(BMARK)$(EXE) $(C_LIBS)

compile-prof: $(C_SRC)
	@echo
	@echo -e "Benchmark\t\t- $(BMARK)"
	@$(COMPILE_PG) $(BASE_SRC) $(COMMON_SRC) $(C_SRC) -o $(BMARK)$(EXE)

matlab-run:
	@echo
	@echo -e "Benchmark\t\t- $(BMARK)"
	@echo -e "Data set\t\t- $(INPUT)"
	@cd $(M_DIR); $(MATLAB_PATH) -glnx86 -nosplash -nodisplay -r "script_run_profile('$(M_DATA)', '$(M_RESULT)', '$(INPUT)', '$(M_COMMON)', '$(M_TOOLBOX)'); quit" | tee $(MTIMING_DIR)/Matlab_$(INPUT).txt

mcc-run:
	@echo Generating a C standalone application
	cd $(M_DIR); $(MATLAB_PATH) -nosplash -nodesktop -r "mcc -m -v script_run_profile -d $(M_RESULT); quit"

all: c-run matlab-run mcc-run

clean:
	@-rm $(BMARK)
